"""
Extract the embedded (encoded bytecode, charset) pair from a Hercules-obfuscated
Lua source file.

Hercules wraps the obfuscated payload in a runtime stub generated by
`VMGenerator.lua`. The relevant output line is:

    WrapState(BcToState('<encoded>','<charset>'),(getfenv and getfenv(0)) or _ENV)()

After variable-renaming, `WrapState` and `BcToState` become random identifiers,
but the surrounding structure is preserved. We use a tolerant regex to locate
the call and capture both string literals.

Decoding pipeline (mirrors `VMStrings.lua`):

    1. The `<charset>` string is a sequence of `\\NN` escapes — one byte per
       escape. It defines a base-N alphabet (N = len(charset)).
    2. The `<encoded>` string is similarly a sequence of `\\NN` escapes that
       decode to bytes forming the *inner* string.
    3. The inner string is split on `_` (byte 95). Each chunk is a base-N
       number whose digits are charset characters. The numeric value of each
       chunk is one byte of the original serialized bytecode stream.
    4. The serializer wrote `byte + '\\'` for each value, so the resulting
       byte stream alternates [data, '\\', data, '\\', ...]. The actual
       bytecode bytes are the even-indexed ones.

After step 4 we have the raw buffer that `deserializer.deserialize` accepts.
"""

from __future__ import annotations
import re
import sys
from typing import Tuple, Optional

# Lift Python's default int-string conversion limit: encoded chunks can be
# arbitrarily long when the base is small (e.g., base-2 would explode).
sys.set_int_max_str_digits(2_000_000)

# Locate: NAME(NAME('...','...'),(getfenv and getfenv(0))or _ENV)()
# The two string literals can be very long.
PAYLOAD_RE = re.compile(
    r"(\w+)\((\w+)\('([^']*)','([^']*)'\),\(getfenv and getfenv\(0\)\)or _ENV\)\(\)"
)


def _decode_backslash_string(s: str) -> bytes:
    """Decode a string of `\\NN` escapes into raw bytes.

    The obfuscator emits each byte as `\\<decimal>` with no padding, so we
    greedily consume digits following every backslash. Non-escape characters
    are kept as-is (their byte value).
    """
    out = bytearray()
    i = 0
    n = len(s)
    while i < n:
        ch = s[i]
        if ch == "\\" and i + 1 < n:
            j = i + 1
            num = ""
            while j < n and s[j].isdigit():
                num += s[j]
                j += 1
            if num:
                out.append(int(num) & 0xFF)
                i = j
                continue
        out.append(ord(ch) & 0xFF)
        i += 1
    return bytes(out)


def find_payload(src: str) -> Optional[Tuple[str, str, str, str, int]]:
    """Locate the WrapState(...) call inside `src`.

    Returns (wrap_fn_name, deser_fn_name, encoded_str, charset_str, match_pos)
    or None if no Hercules payload is found.
    """
    m = PAYLOAD_RE.search(src)
    if not m:
        return None
    return (m.group(1), m.group(2), m.group(3), m.group(4), m.start())


def decode_payload(encoded_str: str, charset_str: str) -> bytes:
    """Decode the (encoded, charset) pair into raw Hercules bytecode bytes."""
    charset_bytes = _decode_backslash_string(charset_str)
    if not charset_bytes:
        raise ValueError("Empty charset")
    base = len(charset_bytes)
    decode_lookup = {chr(charset_bytes[i]): i for i in range(base)}

    # Step 1: encoded_str -> inner byte string (the base-N text representation).
    inner = _decode_backslash_string(encoded_str).decode("latin-1")

    # Step 2: split on "_" and base-N decode each chunk to a single byte.
    raw = bytearray()
    for chunk in inner.split("_"):
        if not chunk:
            continue
        n = 0
        for ch in chunk:
            v = decode_lookup.get(ch)
            if v is None:
                raise ValueError(f"Character {ch!r} not in charset")
            n = n * base + v
        if n < 0 or n > 0xFF:
            raise ValueError(f"Decoded value {n} out of byte range")
        raw.append(n)

    # Step 3: serializer interleaved each data byte with a literal backslash.
    # Strip the backslash separators (every odd-indexed byte).
    data = bytes(raw[0::2])
    return data


def is_hercules(src: str) -> bool:
    """Quick check: does this source look like a Hercules-obfuscated file?"""
    # Watermark line from `manifest.output.watermark_text` and older versions.
    head = src[:300]
    if "Hercules" in head and "Obfuscated by" in head:
        return True
    # Fallback: detect the runtime payload.
    return find_payload(src) is not None
